### ISSUE TITLE
For double sided cards, provide a way to view the backside of the card in the combo detail page

### ISSUE THREAD

**Issue by crookedneighbor** [SpaceCowMedia/commander-spellbook-site#131]
as an example, /combo/8556/ uses sword of the realms, but since it's the back side of the card, Halvar is shown instead.

**Comment by crookedneighbor** [comment]
Thinking something in the admin UI for the combo would have a toggle for displaying the backside for the combos that have a back side to a card.

**Comment by crookedneighbor** [comment]
The way Scryfall does it is very nice: 
![Screen Shot 2021-05-23 at 1 38 13 PM](https://user-images.githubusercontent.com/2916945/119272631-868c5b80-bbcc-11eb-922e-d8d26932e5da.png)

**Comment by crookedneighbor** [comment]
Reached out to the Scryfall devs to ask if we can just use the svg they created for this. If not, we can just use: https://fontawesome.com/icons/undo-alt?style=solid

**Comment by GordonsKitchen** [comment]
When this is implemented, it would be good if we could specify in the backend what side of the card to show when the combo opens. So if the combo uses the back of a card, we can tell the site to show that side first since it is the side that is relevant to the combo. (Default: Front face)
