### ISSUE TITLE
Returning to search from a combo page shouldn't reload the combos

### ISSUE THREAD

**Issue by crookedneighbor** [SpaceCowMedia/commander-spellbook-site#138]
Reported https://twitter.com/Lewandowsky_ph/status/1381732352708214789?s=20

# Describe the Problem

> One more thing to look at is maybe buffering the results, when I browse a long list, and click a combo, when I go back, the results are loaded again and my browser can't go that deep and I lose the point where I was before.

Part of this problem is due to the artificial delay we have when making API requests after the data has been cached locally (done mostly so the transition to a proper API will not be so painful). 

Another thing we'll have to make sure of is returning to the same spot on the page, and if we can, highlight the combo that was chosen previously to make it easier to find where you left off.

**Comment by ldeluigi** [comment]
Solved with pagination
