### ISSUE TITLE
Support is:commander and commander:card-name in searching

### ISSUE THREAD

**Issue by crookedneighbor** [SpaceCowMedia/commander-spellbook-site#145]
This would return combos that

a) have a commander in them
b) have a color identity matching the commander

Down the line, once this data is exposed, we can use it 

* to link to the edhrec combo page for the commander
* link to a search for other combos with the commander `commander="card name"`

**Comment by ldeluigi** [comment]
Obsolete from next release (already available for preview)

`commander="card name"` now searches for combos that require card name as commander to work
