### ISSUE TITLE
Improve Combo Link Preview Image

### ISSUE THREAD

**Issue by crookedneighbor** [SpaceCowMedia/commander-spellbook-site#153]
The current image we use when previewing combos is the art from the _first_ card in the combo. It would be cool if instead we did something like the images of combos that the Twitter account has been posting: http://twitter.com/CommanderSpell/status/1385624692917108737

We should be able to take a screenshot of a page with puppeteer: https://buddy.works/guides/how-take-screenshots-with-puppeteer-headless-chrome

As a short term solution, we could just grab a picture of the combo page when generating the pages. Ultimately, would be nice to create a dedicated preview page that formats them like the Twitter posts.

**Comment by ldeluigi** [comment]
Related to #480

**Comment by yellingatcode** [comment]
@ldeluigi can this one be closed out with the #480 fix in place?

**Comment by ldeluigi** [comment]
Sure
