### ISSUE TITLE
Create tooltip/dropdown with list of searchable combo results

### ISSUE THREAD

**Issue by CVPhelan** [SpaceCowMedia/commander-spellbook-site#161]
We can advanced search via combo result, there is some predictive text in the field, but a dropdown of options of standardized combo results would be helpful, especially for editors, as the style guide just tells them to look at the site for valid combo results. Will probably need to consult with discord to get a proper list.

**Comment by crookedneighbor** [comment]
The drop down list in advanced search only includes results that are in at least 30 combos, so there is already some filtering going on here.

**Comment by CVPhelan** [comment]
So when I was messing with it if I typed in "win" then "win the game" would
auto fill but I didnt see a dropdown where I could peruse all the results
with at least 30 combos. I think seeing a list like that would help new
users understand the kinds of things they can search for and would help
editors as well.

**Comment by crookedneighbor** [comment]
Oh, we have that already: https://commanderspellbook.com/meta/results/

**Comment by CVPhelan** [comment]
Lol one day I'll learn to use my eyeballs

**Comment by crookedneighbor** [comment]
It’s not a page we publicize and will likely be retired when the metrics page is re-instated.
