### ISSUE TITLE
Card Name Shortcuts

### ISSUE THREAD

**Issue by AppleSaws** [SpaceCowMedia/commander-spellbook-site#177]
Rather than writing out the card name in every case, there could be support for a shortcut that would be autofilled with a card name. For example, {c1} would be replaced with the name of the card in column 1.

Could potentially interfere with dymanic card ordering, but the displayed ordering doesn't  necessarily have to match the order in the sheet.

Also runs into potential issues with legends whose names are supposed to be abbreviated, we might need to make a list of exceptions, or just handle those manually?

**Comment by ldeluigi** [comment]
Not needed anymore with the backend
