### ISSUE TITLE
Do Not Trim Spaces in card names inside quotes

### ISSUE THREAD

**Issue by crookedneighbor** [SpaceCowMedia/commander-spellbook-site#179]
# Describe the Problem

We typically trim extra white space from tokens for card names, but in the case of a quoted card name, we'd want to respect the white space at the end or beginning as intentional.

See https://discord.com/channels/673601282946236417/728339448558911508/884485410112299008

**Comment by ldeluigi** [comment]
Solved in next release (already available for preview)
