### ISSUE TITLE
Custom "Combo Not Found" page

### ISSUE THREAD

**Issue by crookedneighbor** [SpaceCowMedia/commander-spellbook-site#187]
In the eventual future where combos are managed in a control panel and backed by a database, deleting a combo will ask the deleter to choose an option for why it was deleted. Possibly something like:

- Combo never worked
- Rules Change Makes the Combo Not Work
- Duplicate with x combo
- Other - written explanation

This will have the benefit of keeping the combo in the database without exposing it to our users, so if a new proposed combo tries to propose the same cards, they'll get a rejection with an explanation for why it was deleted.

In the meantime, while we wait for the combo database control panel, we can simply have the 404 pages for combos say something like:

```
Oops. This combo no longer exists here. It was either non-functional, a duplicate of another combo, or was eaten by a Vizzerdrix. One of those three.
```

**Comment by ldeluigi** [comment]
This issue has been superseded by https://github.com/SpaceCowMedia/commander-spellbook-backend/issues/254

I'll note the suggestion to append a message as to why some combo has been deleted
