### ISSUE TITLE
Multiple combo "Variations" (same cards, slightly different prereqs/results) within a combo

### ISSUE THREAD

**Issue by AppleSaws** [SpaceCowMedia/commander-spellbook-site#188]
The idea would be that rather than trying to list these things as separate combos, we could have a way to toggle between the desired version(s) within the same combo. There are lots of ways to do this, from almost having two separate pages, to having a dropdown for the changing field that causes other updates or something, but I think the general principle is worth exploring.

**Comment by ldeluigi** [comment]
The backend allows this
