### ISSUE TITLE
Ability to modify number of cards in combo/separating cards in deck from overall cards

### ISSUE THREAD

**Issue by AppleSaws** [SpaceCowMedia/commander-spellbook-site#189]
Title explains most of it. Some combos need a somewhat specific card (like a mana dork) and should arguably be called 2 card combos. There aren't any real needs to lower cards in combo though.  As an expansion of this idea though, could allow us to track cards on hand, graveyard, library, etc. There's certainly lots of possibilities for a feature like this.

**Comment by ldeluigi** [comment]
The backend allows this
