### ISSUE TITLE
Bug: sort param not considered a valid param when only using it in a search query

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-site#268]
Currently, when you want to search all combos in the database by popularity, you cannot simply do "sort:popularity", as you would expect. You currently have to include extra parameters in order for the query to be executed. For example, doing something like "cards>=2 sort:popularity" will return the desired query (although, no combo on the site has less than 2 cards, so the first part is completely pointless). 

Here is what I mean, in link form: https://commanderspellbook.com/search/?q=sort%3Apopularity
https://commanderspellbook.com/search/?q=sort%3Apopularity%20cards>%3D2

It would be good if users can simply type "sort:popularity" and get the query without needing an additional specification that will either add unwanted results or exclude wanted results; or is completely unnecessary, such as "Cards>=2".

**Comment by ldeluigi** [comment]
Solved in next release (already available for preview)

Sorting has been removed from query
Popularity is an upcoming feature for the backend: https://github.com/SpaceCowMedia/commander-spellbook-backend/issues/180
It will allow sorting by it once it's integrated back
