### ISSUE TITLE
Allow Choice of Card Images

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-site#277]
Sometimes when new sets are spoiled, cards that are reprinted can have images that aren't the best. Since the site currently defaults to whatever Scryfall shows (which is the most recent English printing, by default), these images can show on the site. See the example below with Phyrexian Altar (showing the 2X2 upcoming reprint as the image). It would be good if, as part of the admin controls, we could force a different image to show for _all_ Phyrexian Altar combos, at least for a set length of time.
![image](https://user-images.githubusercontent.com/97813519/174495925-282769ed-9c2c-441e-8bd0-fc86abf8b7e7.png)

**Comment by ldeluigi** [comment]
What do you mean with "set length of time"?
