### ISSUE TITLE
Issues searching for unusual characters

### ISSUE THREAD

**Issue by thirdpolice** [SpaceCowMedia/commander-spellbook-site#291]
Found some unexpected behavior when searching for the characters Ö and Â (which appear on cards Bösium Strip and Khârn the Betrayer).

—If a search has zero results, the result message does not display the unusual character: '0 combos where cards have a value containing "Bsium".'

—If the search ONLY contains unusual characters (searching for "â"), I get the response "No valid search parameters submitted"

However, a search for "Khârn" does correctly lead to the one Khârn combo on site. (There are no Bösium combos on site but I can easily add one to test.)

====
Firefox 104.0.2 for MacOS 11.6.5.

**Comment by thirdpolice** [comment]
This also applies to the character ñ which appears on Robo-Piñata.

**Comment by ldeluigi** [comment]
Solved in next release (already available for preview)
