### ISSUE TITLE
Support Multiple sid parameters

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-site#299]
Currently, when you search multiple "sid" ("spellbookid") commands, it will not work correctly, throwing an error (see below screenshot), and then showing all combos on site. If we can fix it to work, it would be great for giving users a list of combos from the Spellbook bot's deck check feature (it could post a link to the site with all sids listed for ease of scrolling).

Also, the error has a misspelling which needs fixed in the short term anyways.

See: https://commanderspellbook.com/search/?q=sid%3A1500%20sid%3A1600 for an example

![image](https://user-images.githubusercontent.com/97813519/195257212-01df163a-4284-4b3a-94de-2170a1c738d9.png)
![image](https://user-images.githubusercontent.com/97813519/195257242-7baed43e-3f06-4b61-acc8-6c11b69cd83f.png)

**Comment by IamCarbonMan** [comment]
Seconding this. I'm working on a tool that can generate a list of combos fully or partially available in a decklist, it would be really helpful to be able to just output a spellbook url containing all the sids.

**Comment by ldeluigi** [comment]
Solved in next release (already available for preview)
