### ISSUE TITLE
[Combo Finder] Command Zone Specific Combos

### ISSUE THREAD

**Issue by crookedneighbor** [SpaceCowMedia/commander-spellbook-site#339]
Some combos being suggested require a specific commander in the command zone, which means if the deck's commander is different, then there is no way to use those combos.

Currently, there's no system in the combo database to flag programmatically the combo requires a specific commander.

Further, there's no way to deterministically determine the commander of the deck, without the deck list inputter to notate it somehow.

**Comment by ldeluigi** [comment]
Solved in next release (already available for preview)
