### ISSUE TITLE
Leaked API Key

### ISSUE THREAD

**Issue by Bren-Square** [SpaceCowMedia/commander-spellbook-site#345]
Just an FYI: Even though you've probably taken the necessary precautions to secure this API key, it is still not recommended to make it visible in your source. There is no knowing what kind of harm it may cause if permissions are not properly set and someone goes poking around. I'd suggest interpolating it in some way via env var or other injection technique at runtime. 

https://github.com/Commander-Spellbook/website-v2/blob/882352fa16b53053d1639714a60b38f8c4c3a8b2/scripts/download-data/get-google-sheets-data.ts#L15

**Comment by ldeluigi** [comment]
FYI: That API key is also used by some third parties to access the data programmatically and was pasted many times in the discord server

**Comment by ldeluigi** [comment]
The sheet is now private
