### ISSUE TITLE
On-Site FAQs

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-site#392]
It would be good to have an on-site FAQs section. Our current FAQs sits in a Google Doc, but isn't the easiest to find. It'd be much easier if there was an on-site page for it, with a direct link.

Current FAQs: https://docs.google.com/document/d/1AUEdKKvViHADXQ5Mr7cqw2AHl47eHvqTaNtfYeR8P9M/edit?usp=sharing

See: https://edhrec.com/faq for some form of model.

**Comment by ldeluigi** [comment]
![image](https://github.com/SpaceCowMedia/commander-spellbook-site/assets/44567586/b322fb47-a5c0-40e5-b45c-b99bd536c1a2)
