### ISSUE TITLE
Discord Embeds Don't Have Site Name / Embed Images for Sagas

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-site#397]
Embeds don't have the site name as they should

What it should look like:
![image](https://user-images.githubusercontent.com/97813519/229915015-a54848b5-9494-46ad-bb2c-fd2d773c622b.png)

What it looks like:
![image](https://user-images.githubusercontent.com/97813519/229915113-815754d7-c8d2-46b5-b5fc-4e41e092953b.png)

**Comment by ldeluigi** [comment]
Related to #480

**Comment by ldeluigi** [comment]
Solved with #480
