### ISSUE TITLE
Maximizing Window Causes Reload of Search Pages

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-site#399]
When you have the window below maximum scale, and then maximize the window, sometimes the search pages will reload. It's a bit odd, because it doesn't always happen.

At :07 you can see the reload. I then minimize and maximize again at :16 (which doesn't show very well in the video) and it doesn't reload.

(Using latest version Opera)

https://user-images.githubusercontent.com/97813519/229936590-f81cfcf2-9803-4cf0-9349-d7808694fbcc.mp4

There's another issue in here as well - if you notice in the video, when it has the "Looking for Combos" screen (see around the 0:10 mark), it says "No valid search parameters submitted", even though there are valid search parameters, and it brings up the page afterwards. This is also sporadic - I have noticed this just from doing a search from the main page, but I can't repeat it regularly, so I'm not sure what is causing it.

**Comment by ldeluigi** [comment]
It's Opera
