### ISSUE TITLE
Multiple Sort Params Returns Unset Error

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-site#400]
If you add multiple search parameters to a query, it returns an error message of "[object Object]". I'm assuming this should say something like "Multiple search parameters are not supported" (which I believe used to be the old message that would show, or at least, something similar). 

With 2 sort queries:
![image](https://user-images.githubusercontent.com/97813519/229938428-6cc3c73b-0bc9-4df7-a981-9c29a4c946d3.png)

With 1 sort query (this is as it should be):
![image](https://user-images.githubusercontent.com/97813519/229938492-251e5782-7691-41ee-9bbf-df162f7a7a9b.png)

**Comment by ldeluigi** [comment]
Sort params have been removed from queries to avoid logic contraddictions.
Solved in next release (already available for preview)
