### ISSUE TITLE
Sort By Date Missing from Sort Dropdown

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-site#401]
The option to sort the query by date is missing from the dropdown box. Typing "sort:created" still works.

Also, a minor thing related to this, can it be changed so the default sort is descending (newest -> oldest)? Currently, it is ascending (oldest -> newest), but I think it makes more sense to see the newest combos first.

![image](https://user-images.githubusercontent.com/97813519/230518846-d555b6e8-8fa1-4a61-a71b-f23298ee62fb.png)

**Comment by ldeluigi** [comment]
Solved in next release (already available for preview)
