### ISSUE TITLE
Warn the users before they submit a variant suggestion 6 or more cards

### ISSUE THREAD

**Issue by ldeluigi** [SpaceCowMedia/commander-spellbook-site#447]
# Describe the Problem
Form Discord:
> For combo submissions, we should consider adding a warning of some sort for if a submitter adds a sixth card. Basically just add in the limitations we have for adding combos to the site or rewording it a bit.

**Comment by accassid** [comment]
What specific message do we want to warn the users with?

**Comment by ldeluigi** [comment]
From Discord:

> Draft 2:
>
> “Warning: This combo might be denied because it is over our five-card maximum. These tips will increase the chances of the combo making it onto Commander Spellbook:
> * If a card has many replacements in this combo’s color identity, cut it and use the generic card template instead. For example, “A Dragon creature” or “A way to give indestructible” can replace a specific card.
> * Cut any cards that are not required to keep the combo going, even if they are needed to win the game. We don’t need to list Blood Artist or Impact Tremors on every page.”
