### ISSUE TITLE
"No valid search paramaters submitted" message appears before search is complete

### ISSUE THREAD

**Issue by thirdpolice** [SpaceCowMedia/commander-spellbook-site#449]
# Describe the Problem
<img width="691" alt="Screenshot 2023-11-27 at 15 11 33" src="https://github.com/SpaceCowMedia/commander-spellbook-site/assets/8032571/63133c1f-c33d-43b6-9aa5-c2c950e7a339">

If the search bar is taking a particularly long time to load, the text "No valid search parameters submitted" will sometimes appear prematurely. The search then eventually completes, showing the correct results or leading to the one unique page.

# Browser and Operating System Information
Opera One(version: 104.0.4944.72) (x86_64)
macOS Version 11.6.5

**Comment by ldeluigi** [comment]
Solved in next release (already available for preview)
