### ISSUE TITLE
Add support for searching / and + symbols

### ISSUE THREAD

**Issue by thirdpolice** [SpaceCowMedia/commander-spellbook-site#453]
Forward slashes and plus signs are ignored in the frontend search, making it impossible to search for, e.g. 'steps:"+1/+0"' and leading to false results such as 'steps:20' returning variants that mention "+2/+0".

EDIT: A better example, to show its importance: we track +1/+1 counters as a standard result, and this makes it difficult to find combos with that output.

**Comment by thirdpolice** [comment]
The error message is broken too.

<img width="321" alt="Screenshot 2023-12-22 at 15 07 20" src="https://github.com/SpaceCowMedia/commander-spellbook-site/assets/8032571/5bd1ffea-452f-4edf-9771-dafd5cee37ef">

**Comment by ldeluigi** [comment]
Gj
