### ISSUE TITLE
"permanents" wrongly used in prereq

### ISSUE THREAD

**Issue by ldeluigi** [SpaceCowMedia/commander-spellbook-site#458]
# Describe the Problem
The prereq of a combo display "other permanents" without checking if the previously named cards are actual permanents.

# Steps to Reproduce
https://commanderspellbook.com/combo/28895/

**Comment by yellingatcode** [comment]
@ldeluigi I don't understand what is needed here.  Could there please be more specifics on what is needing to be shown?

**Comment by ldeluigi** [comment]
Hit the Mother Lode is not a permanent so "All other permanents" should instead say "all other cards" I think

**Comment by yellingatcode** [comment]
So should this be a static change to just "All permanents" or should there be some check of the cards?

**Comment by ldeluigi** [comment]
Ideally, if any aforementioned card is a permanent it should say "all other" otherwise "all permanents" but this means to refactor the whole requirements generator to take into account card type lines taken from the card dto
