### ISSUE TITLE
DFC Deck Counts Always Show Zero

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-site#470]
I pointed this out in Discord on 1/10 but moving it here for documentation. All DFC cards show 0 decks when they shouldn't. For example, Toralf, God of Fury + Star of Extinction shows 0 decks, despite Star being in ~85% of Toralf decks.

Deloo had mentioned this may be an EDHREC issue. I'm not sure if it is or isn't, and if there is something we can do to get these deck counts correct again.

Here's some links if you want to look for yourself: 
https://commanderspellbook.com/search/?q=toralf
https://commanderspellbook.com/search/?q=birgi

![image](https://github.com/SpaceCowMedia/commander-spellbook-site/assets/97813519/f63336b8-1b78-4066-98d9-36a1b5d49a51)

**Comment by ldeluigi** [comment]
Solved by @keattz from edhrec (thanks!)
