### ISSUE TITLE
Spoiler Cards Show as Banned

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-site#473]
Spoiler cards show as banned in commander, along with providing the "spoiler" warning. This prevents them from showing in searches due to "legal:commander" being automatically added. 

![image](https://github.com/SpaceCowMedia/commander-spellbook-site/assets/97813519/caaa1dd7-0aed-4c58-8498-9c6d8455c046)

Link to Discord Convo: https://discord.com/channels/752903319072276540/788902322469470278/1197645961015611473
Link to Combo shown in picture: https://commanderspellbook.com/combo/2829-3490-5346/

**Comment by ldeluigi** [comment]
Fixed by the backend
