### ISSUE TITLE
Sorting for Combos With Zero Decks Is Inconsistent

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-site#488]
It seems to me that the sorting the site does when combos have a deck count of 0 is inconsistent and doesn't seem to follow any form of logic. Before, the sorter would sort by EDHREC # decks, and then by color identity (after that I'm not sure). It doesn't seem that's the case anymore. See: https://commanderspellbook.com/search/?q=cabaretti%20

Before it would sort by Color Identity in descending number of colors (5s to 4s to 3s etc.). I personally always said it should have been sorted the opposite (colorless, 1 color, 2 color, etc.), because the fewer colored combos have higher potentials to be useful due to the sheer increase of decks that can use them. Either way, the sorting should follow a hierarchy that makes sense.

**Comment by ldeluigi** [comment]
Now they are sorted by identity_count, then by cards_count, then by reverse creation date
