### ISSUE TITLE
Unchanged Queries Do Not Load Results From Combo Page

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-site#493]
When you are on a combo page, if you have a query in the search bar, it will not reload the search page unless you change the query, even if the query has 2 or more results.

To reproduce:
1. Type in any query that'll yield 2+ results
2. Click on any combo page that comes up
3. Go to the search bar, which should have the query in it, and click enter to reload. It will do nothing. **Do not change the query when you do this or it will load.**

**Comment by ldeluigi** [comment]
this is not the case anymore as the search bar gets emptied in combo pages
