### ISSUE TITLE
Issue with autocomplete UX

### ISSUE THREAD

**Issue by ldeluigi** [SpaceCowMedia/commander-spellbook-site#523]
# Describe the Problem
Just a UI bug for the combo form, when you're selecting a generic card, when the generic template you're selecting for doesn't fall into one of the current categories the dropdown doesn't give any way of hiding itself, and it blocks the buttons below it

**Comment by yellingatcode** [comment]
I don't see this behavior, is there better test data?

![image](https://github.com/user-attachments/assets/db878717-89d9-4025-81d1-da174e150205)
![image](https://github.com/user-attachments/assets/7e90b4ce-3270-4115-804c-16fea8fbbcc3)

**Comment by ldeluigi** [comment]
I can't reproduce it anymore, apparently the bug has been removed
