### ISSUE TITLE
Modify Card States for Zones with One Card to not List Names Twice

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-site#530]
When a zone shows with only one card listed, and that card has something specified in the "starting state" box on the backend, this is how it shows:
![image](https://github.com/user-attachments/assets/3d8fceca-5653-4bd6-adea-5643137b71f8)

I think having "Conspiracy" listed here twice is redundant, since we don't need to specify what card has the state due to there only being one card. I think taking out the second Conspiracy would be ideal. So here it would say: "Conspiracy on the battlefield (with "Rat" chosen). If more than one card / template is listed on the same line, then the current behavior should stay the same.

I apologize if this is a backend fix more than a frontend, I wasn't exactly sure which GitHub to throw it into. Feel free to move it if you'd like.

**Comment by yellingatcode** [comment]
@GordonsKitchen What combo is this so I have an example :)

**Comment by GordonsKitchen** [comment]
@yellingatcode https://commanderspellbook.com/combo/4875-5853/

**Comment by ldeluigi** [comment]
solved!
